import { build } from 'esbuild';
import { readFile, readdir, writeFile } from 'node:fs/promises';

const result = await build({
  entryPoints: ['entry.mjs'],
  outfile: 'parser.mjs',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  minify: true,
  metafile: true,
  banner: { js: '// Generated by npm run build; do not edit. See LICENSES.txt.' },
});
const packages = [...new Set(Object.keys(result.metafile.inputs)
  .map(input => input.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)/)?.[1])
  .filter(Boolean))].sort();
const licenses = [];
for (const name of packages) {
  const directory = `node_modules/${name}`;
  const metadata = JSON.parse(await readFile(`${directory}/package.json`, 'utf8'));
  const license = (await readdir(directory)).find(file => /^license(?:\.|$)/i.test(file));
  if (!license) throw new Error(`Missing license for ${name}`);
  licenses.push(`${name}@${metadata.version}\n${await readFile(`${directory}/${license}`, 'utf8')}`);
}
await writeFile('LICENSES.txt', licenses.join('\n\n'));
