#!/usr/bin/env bash
# Auto-generated by fm-release-receipt-check.sh.
# The watcher validates these bytes before execution.
export FM_HOME=/home/rich/.no-mistakes/evidence/01M2AF7N7QG8BANBN1NGSWQZD6/live-production-release-receipt-20260912
export FM_RELEASE_SPEC_FILE=/home/rich/.treehouse/firstmate-709e0b/12/firstmate/config/release-receipt.json
export FM_RELEASE_APP_DB_ENV_FILE=/home/rich/dev/lalo-admin/.env
exec /home/rich/.no-mistakes/worktrees/7ce0540b75f4/01M2AF7N7QG8BANBN1NGSWQZD6/bin/../bin/fm-release-receipt-check.sh check
